apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phabricator.fullname" . }}
  labels:
    {{- include "phabricator.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.phabricator.mysql.password | b64enc | quote }}
