apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-self-service-password.fullname" . }}
  labels:
    {{- include "ldap-self-service-password.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_PASS: {{ .Values.lssp.ldap.password | b64enc | quote }}
